server:
  port: 9092
# database config
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2 # 通过浏览器访问H2数据库, http://127.0.0.1:9092/h2
  sql:
    init:
      mode: always
      schema-locations:
        - classpath*:sql/ytdp.sql
        - classpath*:sql/ytdp_data_api_schema.sql
        - classpath*:sql/ytdp_org_schema.sql
      continue-on-error: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true                 # 设置事务自动提交
      maximum-pool-size: 10             # 设置最大连接数
      minimum-idle: 2                   # 设置最小空闲连接数
      connection-test-query: select 1
      connection-timeout: 20000         # 设置连接超时时间，单位ms

  # redis config
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        enabled: true
        max-idle: 8                   # 连接池最大空闲连接数, 默认值8, 负数表示无限量的空闲连接
        min-idle: 0                   # 连接池最小空闲连接数, 默认值0
        max-active: 16                # 连接池分配的最大连接数, 默认值8
        max-wait: -1                  # 连接池耗尽时, 抛出异常前阻塞等待时间, 负数表示无限期等待
      shutdown-timeout: 100           # 宕机超时时间, 默认100ms
